name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: swiftlint lint --strict
      
    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -project MovieDataService.xcodeproj \
          -scheme MovieDataService \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Upload test coverage
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: build/reports/coverage
        
    - name: Cache SwiftLint
      uses: actions/cache@v3
      with:
        path: .swiftlint-cache
        key: ${{ runner.os }}-swiftlint
